<?php

declare(strict_types=1);

namespace AndyDefer\LaravelChronos\ValueObjects;

use AndyDefer\DomainStructures\Abstracts\AbstractValueObject;
use AndyDefer\DomainStructures\Utils\Associative;
use InvalidArgumentException;

/**
 * Immutable Value Object representing an available time slot.
 *
 * A slot is a contiguous block of available time between a start and end datetime,
 * with a specific duration. Slots are generated by analyzing availability and
 * removing blocked periods (schedules and impediments).
 */
final class SlotVO extends AbstractValueObject
{
    private DateTimeZuluVO $start;

    private DateTimeZuluVO $end;

    private int $durationInMinutes;

    /**
     * Create a new SlotVO instance.
     *
     * @param  DateTimeZuluVO  $start  The start of the slot
     * @param  DateTimeZuluVO  $end  The end of the slot
     * @param  int  $durationInMinutes  The duration in minutes
     *
     * @throws InvalidArgumentException If start is after end or duration mismatch
     */
    public function __construct(
        DateTimeZuluVO $start,
        DateTimeZuluVO $end,
        int $durationInMinutes
    ) {
        if (! $start->isBefore($end)) {
            throw new InvalidArgumentException('Slot start must be before end.');
        }

        $actualDuration = (int) $start->diffInMinutes($end);
        if ($actualDuration !== $durationInMinutes) {
            throw new InvalidArgumentException(
                sprintf(
                    'Slot duration mismatch. Expected: %d minutes, Actual: %d minutes.',
                    $durationInMinutes,
                    $actualDuration
                )
            );
        }

        $this->start = $start;
        $this->end = $end;
        $this->durationInMinutes = $durationInMinutes;
    }

    /**
     * Create a slot from a start time and duration.
     */
    public static function fromDuration(DateTimeZuluVO $start, int $durationInMinutes): self
    {
        $end = $start->addMinutes($durationInMinutes);

        return new self($start, $end, $durationInMinutes);
    }

    /**
     * Get the start datetime.
     */
    public function getStart(): DateTimeZuluVO
    {
        return $this->start;
    }

    /**
     * Get the end datetime.
     */
    public function getEnd(): DateTimeZuluVO
    {
        return $this->end;
    }

    /**
     * Get the duration in minutes.
     */
    public function getDurationInMinutes(): int
    {
        return $this->durationInMinutes;
    }

    /**
     * Get the duration formatted as a human-readable string.
     */
    public function getDurationFormatted(): string
    {
        $hours = floor($this->durationInMinutes / 60);
        $minutes = $this->durationInMinutes % 60;

        if ($hours > 0 && $minutes > 0) {
            return sprintf('%dh %dm', $hours, $minutes);
        }

        if ($hours > 0) {
            return sprintf('%dh', $hours);
        }

        return sprintf('%dm', $minutes);
    }

    /**
     * Check if this slot overlaps with another time range.
     */
    public function overlapsWith(DateTimeZuluVO $start, DateTimeZuluVO $end): bool
    {
        return $this->start->isBefore($end) && $this->end->isAfter($start);
    }

    /**
     * Check if this slot overlaps with another slot.
     */
    public function overlapsWithSlot(self $slot): bool
    {
        return $this->overlapsWith($slot->getStart(), $slot->getEnd());
    }

    /**
     * Check if this slot is fully contained within another time range.
     */
    public function isContainedIn(DateTimeZuluVO $start, DateTimeZuluVO $end): bool
    {
        return ($this->start->isAfterOrEqual($start) || $this->start->isEqual($start))
            && ($this->end->isBeforeOrEqual($end) || $this->end->isEqual($end));
    }

    /**
     * Check if this slot contains a specific datetime.
     */
    public function contains(DateTimeZuluVO $dateTime): bool
    {
        return $dateTime->isBetween($this->start, $this->end);
    }

    /**
     * Check if this slot is adjacent to another slot.
     */
    public function isAdjacentTo(self $slot): bool
    {
        return $this->end->isEqual($slot->getStart()) || $slot->getEnd()->isEqual($this->start);
    }

    /**
     * Merge with another slot if they are adjacent.
     *
     * @return self|null The merged slot or null if not adjacent
     */
    public function merge(self $slot): ?self
    {
        if (! $this->isAdjacentTo($slot)) {
            return null;
        }

        $start = $this->start->isBefore($slot->getStart()) ? $this->start : $slot->getStart();
        $end = $this->end->isAfter($slot->getEnd()) ? $this->end : $slot->getEnd();
        $duration = (int) $start->diffInMinutes($end);

        return new self($start, $end, $duration);
    }

    /**
     * Split the slot into smaller slots of a given duration.
     *
     * @param  int  $chunkDurationInMinutes  The duration of each chunk
     * @return array<self> Array of smaller slots
     */
    public function split(int $chunkDurationInMinutes): array
    {
        if ($chunkDurationInMinutes <= 0) {
            throw new InvalidArgumentException('Chunk duration must be positive.');
        }

        if ($chunkDurationInMinutes > $this->durationInMinutes) {
            return [$this];
        }

        $slots = [];
        $currentStart = $this->start;

        while ($currentStart->addMinutes($chunkDurationInMinutes)->isBeforeOrEqual($this->end)) {
            $slots[] = self::fromDuration($currentStart, $chunkDurationInMinutes);
            $currentStart = $currentStart->addMinutes($chunkDurationInMinutes);
        }

        // Add remaining time as a slot if any
        $remainingMinutes = (int) $currentStart->diffInMinutes($this->end);
        if ($remainingMinutes > 0) {
            $slots[] = self::fromDuration($currentStart, $remainingMinutes);
        }

        return $slots;
    }

    /**
     * Get the slot as an associative array.
     *
     * @return array{start: string, end: string, duration: int, duration_formatted: string}
     */
    public function toArray(): array
    {
        return [
            'start' => $this->start->getValue(),
            'end' => $this->end->getValue(),
            'duration' => $this->durationInMinutes,
            'duration_formatted' => $this->getDurationFormatted(),
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function getValue(): Associative
    {
        return Associative::from($this->toArray());
    }

    /**
     * Convert to string.
     */
    public function __toString(): string
    {
        return $this->start->toDateTimeString().' - '.$this->end->toDateTimeString().' ('.$this->getDurationFormatted().')';
    }
}
